name: Feature request
description: Suggest something
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: Idea
      description: What do you want added or changed?
    validations:
      required: true
